[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "computer-doc"
authors = [{name = "Guoweikang", email = "guoweikang.kernel@gmail"}]
dynamic = ["version", "description"]
